const Users = [
  { id: "1", name: "Arya", fullname: "Muhammad Arya Nur Sabilillah", gender: "M" },
  { id: "2", name: "Cici", fullname: "Cindi Septa Alaika", gender: "F" },
  { id: "3", name: "Ajun", fullname: "Muhammad Junaedi", gender: "M" },
  { id: "4", name: "Nayla", fullname: "Nayla Putri Azzahra", gender: "F" },
  { id: "5", name: "Toriq", fullname: "Muhammad Toriq Robbani", gender: "M" },
  { id: "6", name: "Zahra", fullname: "Zahra Nurfadila", gender: "F" },
  { id: "7", name: "Firgi", fullname: "Muhammad Firgiawan", gender: "M" },
  { id: "8", name: "Arumi", fullname: "Arumi Maharani", gender: "F" },
  { id: "9", name: "Fadly", fullname: "Muhammad Fadly Syiraz", gender: "M" },
  { id: "10", name: "Cilla", fullname: "Cilla Aureliana", gender: "F" },
  { id: "11", name: "Charlos", fullname: "Charlos Ferdinand Hutagaol", gender: "M" },
  { id: "12", name: "Elina", fullname: "Elina Dwi Prameswari", gender: "F" },
  { id: "13", name: "Fadhil", fullname: "Fadhil Luki Pratama", gender: "M" },
  { id: "14", name: "Tasya", fullname: "Tasya Maharani", gender: "F" },
  { id: "15", name: "Alvio", fullname: "Alvio Reza", gender: "M" },
  { id: "16", name: "Annisa", fullname: "Annisa Firdhaus", gender: "F" },
  { id: "17", name: "Joo", fullname: "Jonathan", gender: "M" },
  { id: "18", name: "Shafa", fullname: "Shafa Najwa", gender: "F" },
  { id: "19", name: "Joshua", fullname: "Joshua Taffarel Chriensa", gender: "M" },
  { id: "20", name: "Aurel", fullname: "Aurelina Fitri", gender: "F" },
  { id: "21", name: "Daffa", fullname: "Daffa Rizqi Wardana", gender: "M" },
  { id: "22", name: "Nabila", fullname: "Nabila Ayudia", gender: "F" },
  { id: "23", name: "Diki", fullname: "Diki Pradana", gender: "M" },
  { id: "24", name: "Indah", fullname: "Indah Ayu Kartika", gender: "F" },
  { id: "25", name: "Adrian", fullname: "Adrian Adzhar", gender: "M" },
  { id: "26", name: "Laras", fullname: "Laras Permata", gender: "F" },
  { id: "27", name: "Imron", fullname: "Imron Alamsyah", gender: "M" },
  { id: "28", name: "Meyza", fullname: "Meyza Nurani", gender: "F" },
  { id: "29", name: "Dani", fullname: "Dani Silaen", gender: "M" },
  { id: "30", name: "Viola", fullname: "Viola Marissa", gender: "F" },
  { id: "31", name: "Dimas", fullname: "Adhimas Dwi Putra", gender: "M" },
  { id: "32", name: "Zahira", fullname: "Zahira Mutia", gender: "F" },
  { id: "33", name: "Rifki", fullname: "Muhammad Rifki", gender: "M" },
  { id: "34", name: "Aqila", fullname: "Aqila Sabrina", gender: "F" },
  { id: "35", name: "Niezar", fullname: "Niezar Putra Pratama", gender: "M" },
  { id: "36", name: "Kayla", fullname: "Kayla Annasya", gender: "F" },
  { id: "37", name: "Ian", fullname: "Adrian Anugrah", gender: "M" },
  { id: "38", name: "Tiara", fullname: "Tiara Alesha", gender: "F" },
  { id: "39", name: "Adit", fullname: "Aditya Surya Pranata", gender: "M" },
  { id: "40", name: "Ayesha", fullname: "Ayesha Latifah", gender: "F" },
  { id: "41", name: "Huda", fullname: "Nurhuda", gender: "M" },
  { id: "42", name: "Selena", fullname: "Selena Ramadhani", gender: "F" },
  { id: "43", name: "Hendri", fullname: "Muhammad Hendri Fadilah", gender: "M" },
  { id: "44", name: "Mika", fullname: "Mika Zahra", gender: "F" },
  { id: "45", name: "Aris", fullname: "Muhammad Faqi Arrizky", gender: "M" },
  { id: "46", name: "Rania", fullname: "Rania Dewi Amanda", gender: "F" },
  { id: "47", name: "Tegar", fullname: "Muhammad Tegar Wahyudin", gender: "M" },
  { id: "48", name: "Luna", fullname: "Luna Maulida", gender: "F" },
  { id: "49", name: "Rafi", fullname: "Muhammad Rafi Athaya", gender: "M" },
  { id: "50", name: "Salsabila", fullname: "Salsabila Humaira", gender: "F" },
];

export default Users;